# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

python:
  install:
    - method: pip
      path: .

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: "env-readthedocs.yml"

sphinx:
  configuration: doc/conf.py
