#!/usr/bin/env python
"""Fix Python-based executables so that they are run with a framework build"""
from argparse import ArgumentParser
from distutils.spawn import find_executable


OLD = '/bin/python'
NEW = '/python.app/Contents/MacOS/python'

argparser = ArgumentParser(description=__doc__)
argparser.add_argument('exe', type=str, nargs='?', default='eelbrain', help="Name of the executable to fix")

if __name__ == '__main__':
    args = argparser.parse_args()

    path = find_executable(args.exe)

    with open(path) as fid:
        text = fid.read()

    if OLD not in text:
        raise RuntimeError("%r not in file:\n%s" % (OLD, text))

    text = text.replace(OLD, NEW)

    with open(path, 'w') as fid:
        fid.write(text)
