# Eelbrain documentation build configuration file, created by
# sphinx-quickstart on Tue Mar 29 23:16:11 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from datetime import datetime
from pathlib import Path
from packaging.version import Version
import os
import sys

import eelbrain
import eelbrain.datasets._alice
import mne
import sphinx.util.logging

logger = sphinx.util.logging.getLogger("eelbrain")

need_path = str(Path(__file__).parent)
if need_path not in sys.path:
    sys.path.append(need_path)  # for conf.NameOrder and conf.use_pyplot

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

autoclass_content = 'class'  # 'both'

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.4.3'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc', 'sphinx.ext.autosummary',  # default
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',  # http://sphinx.pocoo.org/ext/intersphinx.html
    'sphinx.ext.linkcode',  # source links to GitHub
    'sphinx.ext.napoleon',  # https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
    'sphinxcontrib.bibtex',  # https://sphinxcontrib-bibtex.readthedocs.io
    'sphinx_gallery.gen_gallery',  # https://sphinx-gallery.github.io
    'sphinx_rtd_theme',  # https://sphinx-rtd-theme.readthedocs.io/
]
# enable to have all methods documented on the same page as a class:
# autodoc_default_flags=['inherited-members']
autosummary_generate = True
autodoc_typehints = "description"

# Napoleon settings
napoleon_google_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_special_with_doc = False
napoleon_use_param = True
napoleon_use_ivar = False  # render attributes as directives, which creates cross-reference targets
napoleon_use_keyword = True
napoleon_use_rtype = True

bibtex_bibfiles = ['publications.bib']

qualname_overrides = {
    "eelbrain._data_obj.NDVar": "eelbrain.NDVar",
}


def linkcode_resolve(domain, info):
    """Resolve source code links to GitHub."""
    import importlib
    import inspect
    if domain != 'py' or not info['module']:
        return None
    try:
        mod = importlib.import_module(info['module'])
        obj = mod
        for part in info['fullname'].split('.'):
            obj = getattr(obj, part)
        obj = inspect.unwrap(obj)
        fname = inspect.getfile(obj)
        source, start = inspect.getsourcelines(obj)
    except Exception:
        return None
    # Make path relative to the repo root (works for editable installs);
    # fall back to site-packages-relative path (e.g. on ReadTheDocs)
    repo_root = Path(__file__).parent.parent
    try:
        rel = Path(fname).relative_to(repo_root)
    except ValueError:
        pkg_root = Path(eelbrain.__file__).parent.parent
        try:
            rel = Path(fname).relative_to(pkg_root)
        except ValueError:
            return None
    end = start + len(source) - 1
    pkg_version = Version(eelbrain.__version__)
    ref = 'main' if pkg_version.is_devrelease else f'v{pkg_version.public}'
    return f'https://github.com/Eelbrain/Eelbrain/blob/{ref}/{rel.as_posix()}#L{start}-L{end}'


################################################################################
# Sphinx-Gallery
################################################################################

def use_pyplot(gallery_conf, fname):
    eelbrain.configure(frame=False)


example_order = {
    '../examples/datasets': [
        'intro.py',
        'dataset-basics.py',
        'align.py',
        'ndvar-creating.py',
        'group-level-analysis.py',
    ],
    '../examples/statistics': [
        'models.py',
        'RMANOVA.py',
        'ANCOVA.py',
    ],
    '../examples/mass-univariate-statistics': [
        'permutation-statistics.py',
        'sensor-ttest.py',
        'sensor-anova.py',
        'sensor-lm.py',
        'sensor-two-stage.py',
        'compare-topographies.py',
        'volume-source-space.py',
    ],
    '../examples/plots': [
        'boxplot.py',
        'utsstat.py',
        'colors.py',
        'colormaps.py',
        'customizing.py',
    ],
    '../examples/temporal-response-functions': [
        'trf_intro.py',
        'alice-trf.py',
        'mtrf.py',
        'partitions.py',
        'epoch_impulse.py',
    ],
}


class NameOrder:
    """Specify sphinx-gallery example order as file tree"""

    def __init__(self, src_dir: str) -> None:
        self.src_dir = src_dir

    def __call__(self, item):
        key = str(Path(self.src_dir).relative_to(Path(__file__).parent).as_posix())
        idx = example_order[key].index(item)
        logger.info(f"NameOrder {key} = {idx}: {item}")
        return idx


sphinx_gallery_conf = {
    'examples_dirs': '../examples',   # path to example scripts
    'subsection_order': list(example_order),
    'within_subsection_order': "conf.NameOrder",
    'gallery_dirs': 'auto_examples',  # path where to save gallery generated examples
    'filename_pattern': rf'{os.sep}\w',
    'default_thumb_file': Path(__file__).parent / 'images' / 'eelbrain.png',
    'min_reported_time': 4,
    'download_all_examples': False,
    'reset_modules': ('matplotlib', "conf.use_pyplot"),
    'reference_url': {'eelbrain': None},
    "backreferences_dir": "generated",
}

# Disable tqdm (to avoid progress bar output in example gallery)
os.environ['TQDM_DISABLE'] = '1'
os.environ['MNE_TQDM'] = 'off'

################################################################################
# Bibliography
################################################################################
# import pybtex.plugin
import pybtex.plugin
from pybtex.style.formatting.unsrt import Style
from pybtex.style.sorting.author_year_title import SortingStyle
from pybtex.style.template import field, href


class MySortingStyle(SortingStyle):

    def sorting_key(self, entry):
        author, year, title = SortingStyle.sorting_key(self, entry)
        year = -int(year) if year.isdigit() else 1
        return year, author, title


class MyBibStyle(Style):
    default_sorting_style = MySortingStyle

    def format_url(self, e):
        url = field('url', raw=True)
        return href[url, url]  # will change to href(url)[url]


pybtex.plugin.register_plugin('pybtex.style.formatting', 'year', MyBibStyle)


################################################################################
# Sphinx basics
################################################################################

# Add any paths that contain templates here, relative to this directory.
templates_path = ['templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Eelbrain'
copyright = '%i, Christian Brodbeck' % datetime.now().year

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
def _format_version_display(version_string):
    parsed = Version(version_string)
    display_parts = [parsed.base_version]
    if parsed.pre:
        pre_label, pre_number = parsed.pre
        pre_label = {
            'a': '\N{GREEK SMALL LETTER ALPHA}',
            'b': '\N{GREEK SMALL LETTER BETA}',
        }.get(pre_label, pre_label)
        display_parts.extend((pre_label, str(pre_number)))
    if parsed.dev is not None:
        display_parts.extend(('dev', str(parsed.dev)))
    if parsed.post is not None:
        display_parts.extend(('post', str(parsed.post)))
    return ' '.join(display_parts)


# The displayed version.
version = _format_version_display(eelbrain.__version__)
rst_epilog = f"""
.. role:: project-version

.. |version_title| replace:: :project-version:`{version}`
"""
# The full version, including alpha/beta/rc tags.
release = eelbrain.__version__  # '0.0.3'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['build', 'illustrations', 'images', 'static']

# The reST default role (used for this markup: `text`) to use for all documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
modindex_common_prefix = ['eelbrain.']

# Supress warnings
suppress_warnings = [
    'image.nonlocal_uri',  # badges
    "bibtex.missing_field",  # missing year in some entries
]


# -- Custom Options -----------------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3.8', None),
    'imageio': ('https://imageio.readthedocs.io/en/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
    'mne': ('https://mne.tools/stable', None),
    'nilearn': ('https://nilearn.github.io/stable', None),
    'numpy': ('https://numpy.org/doc/stable', None),
    'pandas': ('https://pandas.pydata.org/docs', None),
    'scipy': ('https://docs.scipy.org/doc/scipy', None),
    'sklearn': ('https://scikit-learn.org/stable', None),
    'surfer': ('https://pysurfer.github.io', None),
}
# http://sphinx.pocoo.org/ext/intersphinx.html


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# new default: alabaster
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further. https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html
html_theme_options = {
    'logo_only': True,
    'includehidden': False,
    'navigation_depth': 2,  # otherwise RTD includes all autosummary sub-headings
}
html_baseurl = os.environ.get('READTHEDOCS_CANONICAL_URL', 'https://eelbrain.readthedocs.io/en/stable/')

# Use the current Read the Docs build URL for copy-paste commands.
environment_yml_url = f"{html_baseurl.rstrip('/')}/_static/environment.yml"
_environment_yml_url_placeholder = '{{ environment_yml_url }}'


def resolve_build_urls(app, docname, source):
    """Resolve URL placeholders that occur inside literal blocks."""
    source[0] = source[0].replace(_environment_yml_url_placeholder, environment_yml_url)


# Types that are rendered without their module, in type hints (see autodoc_typehints_format) and in docstrings inherited from PySurfer
QUALIFIED_NAMES = {
    'BaseEstimator': 'sklearn.base.BaseEstimator',
    'Label': 'mne.Label',
    'Path': 'pathlib.Path',
}


def resolve_reference(app, env, node, contnode):
    """Handle Python references that Sphinx could not resolve.

    Sphinx only searches the current module (set with ``currentmodule``) and the global namespace, so a reference like ``:class:`plot.SensorMap``` fails wherever the current module is not ``eelbrain``. Retry those in the ``eelbrain`` namespace.

    The changelog refers to objects that have since been renamed or removed; leave those as plain text instead of failing the build.

    Connected before intersphinx, so that a target replaced with its qualified name is resolved there.
    """
    if node['refdomain'] != 'py':
        return None
    elif node.get('refdoc') == 'changes':
        return contnode
    target = node['reftarget']
    if target in QUALIFIED_NAMES:
        node['reftarget'] = QUALIFIED_NAMES[target]
        return None
    elif target.startswith('eelbrain.'):
        return None
    return env.domains['py'].resolve_xref(env, node.get('refdoc', env.docname), app.builder, node['reftype'], f'eelbrain.{target}', node, contnode)


# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'images/eelbrain.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'static/eelbrain.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']
html_css_files = ['css/custom.css']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {'**': ['globaltoc.html', 'searchbox.html']}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Eelbraindoc'


# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
# latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
# latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    ('index', 'Eelbrain.tex', 'Eelbrain Documentation', 'Christian Brodbeck', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Additional stuff for the LaTeX preamble.
# latex_preamble = ''

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'eelbrain', 'Eelbrain Documentation', ['Christian Brodbeck'], 1),
]


def setup(app):
    """Set up the Sphinx app."""
    app.connect('source-read', resolve_build_urls)
    app.connect('missing-reference', resolve_reference, priority=400)  # before intersphinx (500)
    # ensure we have the data necessary to build examples
    logger.info("Ensuring example data is available")
    mne.datasets.sample.data_path(verbose=True)
    eelbrain.datasets._alice.get_alice_path(progressbar=True)
