'''
Generate test scipt for example scripts

'''
import os

curdir = os.path.dirname(__file__)
test_dir = os.path.abspath(os.path.join(curdir, '..', 'eelbrain', 'tests'))
dst = os.path.join(test_dir, 'test_examples.py')
example_dir = os.path.abspath(os.path.join('..', 'examples'))

temp = """
def test_{i}():
    "Test {filename}"
    os.chdir({dirpath!r})
    execfile({filename!r})
"""

intro = """# generated by eelbrain/scripts/make_example_tests.py
import os
"""
parts = [intro]

i = 0
for dirpath, _, filenames in os.walk(example_dir):
    rel_dirpath = os.path.relpath(dirpath, test_dir)
    for filename in filenames:
        if filename.endswith('.py'):
            text = temp.format(i=i, filename=filename, dirpath=rel_dirpath)
            parts.append(text)
            i += 1

text = ''.join(parts)
with open(dst, 'w') as fid:
    fid.write(text)
