'''
Generate test scipt for example scripts

'''
import os

curdir = os.path.dirname(__file__)
test_dir = os.path.abspath(os.path.join(curdir, '..', 'eelbrain', 'tests'))
dst = os.path.join(test_dir, 'test_examples.py')
example_dir = os.path.abspath(os.path.join('..', 'examples'))

temp = """
def test_{i}():
    "Test {example_name}"
    exa_dir = os.path.join(examples_dir, {relpath!r})
    exa_file = os.path.join(exa_dir, {filename!r})

    # find required files
    with open(exa_file) as fid:
        text = fid.read()
    filenames = re.findall("# requires: (\w+.\w+)", text)
    text = text.replace("n_samples = 1000", "n_samples = 2")

    # copy all files to temporary dir
    tempdir = mkdtemp()
    dst = os.path.join(tempdir, {filename!r})
    with open(dst, 'w') as fid:
        fid.write(text)
    for filename in filenames:
        src = os.path.join(exa_dir, filename)
        shutil.copy(src, tempdir)

    # execute example
    logging.info("executing from %s" % tempdir)
    plot.configure(show=False)
    os.chdir(tempdir)
    execfile({filename!r}, {{}})

    # delete temporary files
    shutil.rmtree(tempdir)
"""

intro = """# generated by eelbrain/scripts/make_example_tests.py
import logging
import os
import re
import shutil
from tempfile import mkdtemp

from eelbrain import plot

dir_ = os.path.dirname(__file__)
examples_dir = os.path.join(dir_, '..', '..', 'examples')
examples_dir = os.path.abspath(examples_dir)

"""
parts = [intro]

i = 0
for dirpath, _, filenames in os.walk(example_dir):
    relpath = os.path.relpath(dirpath, example_dir)
    for filename in filenames:
        if filename.endswith('.py'):
            example_name = os.path.join(relpath, filename)
            text = temp.format(i=i, example_name=example_name, relpath=relpath,
                               filename=filename)
            parts.append(text)
            i += 1

text = ''.join(parts)
with open(dst, 'w') as fid:
    fid.write(text)

print "Done!"
