name: Tests

on: [push, pull_request]

jobs:
  build-posix:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"  # Lowest version supported on conda-forge
          - os: macos-latest
            python: "3.12"

    steps:
    - uses: actions/checkout@v4
    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies
      run: |
        sudo apt-get update
    - name: Use Mamba to create env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: env-dev.yml
        environment-name: eeldev
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Build eelbrain
      run: pip install --no-deps -e .
      shell: bash -el {0}
    - if: matrix.os == 'ubuntu-latest'
      name: Test without GUI
      shell: bash -el {0}
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        pytest eelbrain --no-gui
    - if: matrix.os == 'macos-latest'
      name: Test with GUIs and code-cov
      shell: bash -el {0}
      run: |
        pytest eelbrain --cov --cov-branch --cov-report=xml
    - if: matrix.os == 'macos-latest'
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
